import type { Metadata } from "next";
import { Sidebar, SidebarBody, SidebarLink, SidebarTitle } from "@/components/sidebar/sidebar";
import { navigationLinks } from "@/components/sidebar/nav-links";
import { ProfileSidebarLink } from "@/components/sidebar/profile-sidebar-link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <div className="flex h-screen">
        <Sidebar>
          <SidebarBody className="justify-between gap-10">
            <div className="flex flex-col flex-1 overflow-y-auto overflow-x-hidden">
              <SidebarTitle />
              <div className="mt-8 flex flex-col gap-2">
                {navigationLinks.map((link, idx) => (
                  <SidebarLink key={idx} link={link} />
                ))}
              </div>
            </div>
            <div>
              <ProfileSidebarLink />
            </div>
          </SidebarBody>
        </Sidebar>
        <main className="flex-1 overflow-y-auto">{children}</main>
      </div>
  );
}
