import type { Metadata } from "next";
import "@/app/globals.css";
import { Navbar } from "@/components/homeLayout/navbar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
        <Navbar />
        {children}
    </main>
  );
}
